environment:
  matrix:
  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $env:JULIA_URL,
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  - ps: Start-FileDownload 'https://github.com/barche/julia-c-struct-test/releases/download/v2.0/structs.v1.0.0.x86_64-w64-mingw32.tar.gz'
  - tar --strip-components=2 -xvzf structs.v1.0.0.x86_64-w64-mingw32.tar.gz

test_script:
  - C:\projects\julia\bin\julia structs.jl
